apiVersion: apps/v1
kind: Deployment
metadata:
  name: pn-apps
  namespace: pn-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pn-apps
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: pn-apps
    spec:
      containers:
      - name: pn-apps
        image: gcr.io/pinknode-infra-gke/pn-apps-custom:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
