name: Chain endpoints
on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  types:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check
      env:
        CI_LOG: 123
      run: |
        yarn install --immutable | grep -v 'YN0013'
        yarn ci:chainEndpoints
    - name: send custom message
      if: ${{ failure() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          The ${{ github.event_name }} event triggered final step.
          echo An WSS API endpoint failed
